// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB690ON3wu4gi5Qb2rD_88WAYFW9UPkJ_U',
    appId: '1:542047676304:web:3dd79a0f7b1199e1cb7515',
    messagingSenderId: '542047676304',
    projectId: 'tyt-book',
    authDomain: 'tyt-book.firebaseapp.com',
    storageBucket: 'tyt-book.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXHjjl1SYmyZ6KX4GJtyHW4UbWtLTbw9w',
    appId: '1:542047676304:android:30efacfe2dcb5367cb7515',
    messagingSenderId: '542047676304',
    projectId: 'tyt-book',
    storageBucket: 'tyt-book.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPOrtiROR6HXOfbeIACjtxkH-ofiu3rU',
    appId: '1:542047676304:ios:7ce123c77f54b859cb7515',
    messagingSenderId: '542047676304',
    projectId: 'tyt-book',
    storageBucket: 'tyt-book.appspot.com',
    iosClientId: '542047676304-21k6llhm1oq6t4moscba327bn56jo45i.apps.googleusercontent.com',
    iosBundleId: 'com.example.ebookTyt',
  );
}
